GNOMAD_V3_GENOMES:
  chroms:
    - "chr22"
    - "chr21"
  scenarios:
    all_nfe:
      props: "1.0, 0.0, 0.0, 0.0, 0.0" # proportion across populations
      n: 10000 # number of samples
    uniform_eurasia:
      props: "0.25, 0.25, 0.25, 0.25, 0.0"
      n: 10000
